import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {ThemeProvider} from "./providers";
import Header from "./components/Header";
import { Head } from 'next/document';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className+" light light:bg-gray-100 dark dark:bg-slate-900"}>
        <ThemeProvider>
            <Header />
            {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
